CacheRepository.md, Operation.md
Updating the doc to reflect discussed changes.
=> Adding changes to support DefaultOperation in all repositories.

pages/DataSource/DeviceStorageDataSource.md, pages/Interactor/Interactor.md, pages/Logger.md, pages/Repository/CacheRepository.md, pages/Repository/RepositoryMapper.md
Complete some examples for Kotlin Reference and update some old reference
Update Logger Swift reference with the last changes
https://github.com/mobilejazz/harmony-swift/pull/18
=> Update kotlin reference + Logger Swift reference

src/sidebars.js
=> Update navigation to include Realm Datasource

docs/best-practices/presenter-specs.md, src/sidebars.js
=> Create presenter specs

docs/best-practices/angular.md, src/sidebars.js
=> Add new Angular guidelines page

docs/other/tips/node.md
Related to the discussion we had on Slack.
=> Clarify the recommended way of managing NPM packages

docs/other/tips/git.md
Hi Alex! I've made few small wording tweaks to your #84 PR.
=> Tweak `merge two repos` explanation

docs/best-practices/dependency-injection.md, docs/best-practices/naming-convention.md, src/css/custom.css, src/theme/CodeBlock/styles.module.css
-  New DI proposal for Angular (and probably NestJS) **⚠️ which departs from the Harmony DI standard**. [Rendered](https://github.com/mobilejazz/harmony-reference/blob/c6d9f34c0792df35ffd11816a9255542b9e819a2/docs/best-practices/dependency-injection.md#angular).
- Improve naming convention table:
=> DOC-4592 :: Improve Angular DI section & improve naming convention table

docs/best-practices/git-standardization.md
* Asana task link: https://app.asana.com/0/409913176844723/1202442694320171
=> DOC-0171 :: Feature :: Document big feature branches GIT workflows

docs/other/tips/terminal.md, src/sidebars.js
Added new terminal tips section.
=> DOC :: new terminal tips section

docs/best-practices/git-standardization.md
Update the doc to reflect the decision of using GitHub Flow in all projects (mobile ones included)
* Asana task link: https://app.asana.com/0/1109863238977521/1202604195875614/f
=> DOC-5614 :: Feature :: Update Git standardization with GitHub Flow

docs/best-practices/git-standardization.md
* Asana task link: https://app.asana.com/0/409913176844723/1202573736041803
=> DOC-1803 :: Feature :: Update Git standardization with platform special case

package-lock.json, package.json
Dependencies upgrade
* Asana task link:
[Upgrade libraries/dependencies from Harmony Reference (even months)](https://app.asana.com/0/0/1202567383862731/f)
=> FRONTEND-2731 :: Feature Internal :: Upgrade libraries/dependencies from Harmony Reference (even months)

docs/best-practices/code-style-lint.md, src/sidebars.js
* Asana task link: https://app.asana.com/0/1200574432121296/1202573168895647/f
=> DOC-5647 :: Feature Internal :: Include in HR linting for PHP

docs/best-practices/documentation.md, src/sidebars.js
* Asana task link: https://app.asana.com/0/1153936548121653/1200920729803596/f
=> DOC-3596 :: Projects Documentation best practices

docs/agreements/rest-api.md, src/sidebars.js
* Asana task link: https://app.asana.com/0/1200574432121296/1202719209886711/f
=> DOC-2862 :: Feature :: Migrate REST API from MJ Wiki to Harmony Reference

docs/best-practices/code-style-lint.md, docusaurus.config.js, package-lock.json
* Asana task link: https://app.asana.com/0/1200574432121296/1202725839238200
=> DOC-8200 :: Feature :: Update Code Style and Linting page for Android

docs/agreements/rest-api.md, src/sidebars.js
* Asana task link: https://app.asana.com/0/1200574432121296/1202969598777943/f
=> DOC-7943 :: Feature :: Update no-RESTful agreement

docs/best-practices/git-standardization.md
* Asana task link: https://app.asana.com/0/1109863238977521/1203004901262502/f
=> DOC-2502  :: Feature ::  Mobile Release Process Specification

docs/other/tips/mysql.md, src/sidebars.js
* Asana task link: https://app.asana.com/0/1109863238977521/1202471105552598/f
=> DOC-2598 :: Feature :: MySQL Documentation

docs/best-practices/angular.md, docs/best-practices/php.md, src/sidebars.js
* Asana task link: https://app.asana.com/0/1109863238977521/1202820092280517/f
=> DOC-0517 :: Feature :: PHP | Add Quotes pattern rule to HR

docs/other/tips/mysql.md
* Asana task link: https://app.asana.com/0/1109863238977521/1203163700736215/f
=> DOC-6215 :: Feature :: MySQL tips about Charset

docs/best-practices/devops.md, src/sidebars.js
* Asana task link: https://app.asana.com/0/1200574432121296/1200996275923170/f
=> DOC-3170 :: Feature :: DevOps Scripts standard Harmony Reference

docs/best-practices/folders-structure.md
**Asana task link:**
https://app.asana.com/0/1109863238977521/1203336006122724/f
**Pull request information:**
Angular standard folders structure added to the documentation
=> FRONTEND-2724 :: Feature :: Add project folder structure agreement to Harmony reference

docs/agreements/scss.md, src/sidebars.js
**Asana task**
https://app.asana.com/0/1109863238977521/1203450043003497/f
Documentation about our last agreement regarding scss usage.
=> DOC-3497 :: Feature :: Document SASS colors & breakpoints patterns
